### ISSUE TITLE
In 0.0.8, debug fails. `TypeError: console.group is not a function`

### ISSUE THREAD

**Issue by dotZak** [soderlind/vscode-phpcbf#14]
With `"phpcbf.debug": true` in the project settings I get the following in the console under `Output` > `Log (Window)`:

```console
[2018-02-21 09:53:55.757] [renderer1] [error] console.group is not a function: TypeError: console.group is not a function
    at PHPCBF.getArgs (/Users/zk/.vscode/extensions/persoderlind.vscode-phpcbf-0.0.8/extension.js:73:21)
    at PHPCBF.format (/Users/zk/.vscode/extensions/persoderlind.vscode-phpcbf-0.0.8/extension.js:96:55)
    at Promise (/Users/zk/.vscode/extensions/persoderlind.vscode-phpcbf-0.0.8/extension.js:252:30)
    at Promise (<anonymous>)
    at Object.provideDocumentFormattingEdits (/Users/zk/.vscode/extensions/persoderlind.vscode-phpcbf-0.0.8/extension.js:244:28)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:629:497
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:622
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:75:657)
    at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:585)
    at e.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:629:451)
```

This prevents the document from being written while debugging to the console is enabled. Discovered this while trying to figure out a problem with formatting for WordPress standards.

VS Code 1.20.1 (2018-02-13)
vscode-phpcbf 0.0.8

**Comment by soderlind** [comment]
Thanks, I'll remove the call to `console.group`

btw, what OS etc are you on ?

**Comment by dotZak** [comment]
macOS High Sierra (10.13.3)

**Comment by badah** [comment]
Same error here. I'm on Ubuntu 17.10 (artful).

**Comment by dorian-marchal** [comment]
Same problem on Ubuntu 16.04

**Comment by garrettw** [comment]
I see this issue still exists. I'm having it on macOS High Sierra (10.13.5) as well.

Could we get a fix for this @soderlind ?

**Comment by jonty-comp** [comment]
Just tried to set up this extension on High Sierra and encountered the same issue.

**Comment by sowiso** [comment]
Same here on Ubuntu 18.04
