### ISSUE TITLE
Doesn't fire the executable

### ISSUE THREAD

**Issue by ethanteague** [soderlind/vscode-phpcbf#8]
Sorry to leave a really generic "it doesn't work" bug report, but this extension doesn't do anything for me. It's not reporting errors or any messages in the Problems window. I do have phpcbf installed, and can execute it successfully on files via command line. I've tried to hardcode the path to the phpcbf executable in my user settings file, but no joy.

**Comment by soderlind** [comment]
OS?
phpcbf version? Run `phpcbf --version` to get the version
And please post your phpcbf settings.

**Comment by ethanteague** [comment]
Ubuntu, `PHP_CodeSniffer version 2.9.2 (stable)`

**Comment by soderlind** [comment]
You should upgrade phpcs/phpcbf to the latest release (3.2.2)

**Comment by ethanteague** [comment]
That doesn't work for the Drupal folks, @soderlind : ```- drupal/coder 8.2.12 requires squizlabs/php_codesniffer >=2.8.1 <3.0 -> satisfiable by squizlabs/php_codesniffer[2.9.x-dev].
    - drupal/coder 8.2.12 requires squizlabs/php_codesniffer >=2.8.1 <3.0 -> satisfiable by squizlabs/php_codesniffer[2.9.x-dev].```

**Comment by ethanteague** [comment]
I take that back - I don't need coder to use the Drupal standard. That said, I upgraded, and the result is the same.

**Comment by soderlind** [comment]
what's your `phpcbf.executablePath` ?

**Comment by ethanteague** [comment]
I've tried using the default provided by the plugin, as well as changing to the executable path revealed by `which phpcbf`: ` "phpcbf.executablePath": "/home/ethan/.config/composer/vendor/bin/phpcbf"`

**Comment by soderlind** [comment]
Did you try `"phpcbf.defug":true` ? It yes, what's the output in the console ?

**Comment by ethanteague** [comment]
I did, and it doesn't output anything.

**Comment by soderlind** [comment]
Nothing at all ? Strange. What's the vs code version you're running ?

**Comment by ethanteague** [comment]
Latest release - just upgraded when prompted this am.

**Comment by soderlind** [comment]
ok. I'll get back to you. I have to install ubuntu an test it myself. I on macOS now.

**Comment by ADmad** [comment]
I am having the same problem as @ethanteague using linux mint (which is based on ubuntu 16.04 LTS).

**Comment by ADmad** [comment]
My apologies, my problem was due to incorrect configuration due to which my custom standard wasn't being used now. Checking the out in console (Help -> Toggle Developer Tools) I was able to fix my issue.

**Comment by ethanteague** [comment]
I am still experiencing this issue, @soderlind. Phpcs is integrated via https://github.com/ikappas/vscode-phpcs and working on my machine. I have checked all perms, paths, etc. for the phpcbf binary, and they all line up with my phpcs binary being used by the ikappas plugin.

**Comment by raptor235** [comment]
I'm having same issues.. just can't seem to get it to work... but seeing this error...

ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at QualityOfLife.onChangeEditorHandler (/Users/bartdabek/.vscode/extensions/HvyIndustries.crane-0.3.8/out/src/features/qualityOfLife.js:29:19)
    at QualityOfLife.vscode.window.onDidChangeActiveTextEditor.editor (/Users/bartdabek/.vscode/extensions/HvyIndustries.crane-0.3.8/out/src/features/qualityOfLife.js:16:68)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:992)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:665:650
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:992)
    at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:663:757)
    at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:587:832)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:587:550)
    at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:586:658)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:586:427)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:585:494
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:588:343
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:749
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:992)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:143:227)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

**Comment by telmen** [comment]
👍

**Comment by ahmadawais** [comment]
I have the same issue on MacOS. No debug nada.

**Comment by tarikhamilton** [comment]
Worked for me up until a week or so ago. Same issue. No debug/logging. phpcs and phpcbf up to date.

**Comment by gauravgoyal** [comment]
I'm also facing the same issue. Nothing in debug information.
